config {
  type: "view",
  schema: dataform.projectConfig.vars.schema,
  tags: ["ga4","raw","cta"]
}

WITH url_exclusions AS (
  SELECT TRIM(x) AS domain
  FROM UNNEST(
    SPLIT(
      '${dataform.projectConfig.vars.page_url_exclusions_csv || "cloudwaysapps.com,wordpressmu,staging"}',
      ','
    )
  ) AS x
),

base AS (
  SELECT
    event_timestamp,
    TIMESTAMP_MICROS(event_timestamp) AS event_ts,
    DATE(TIMESTAMP_MICROS(event_timestamp)) AS event_date,

    event_name,

    user_pseudo_id,

    event_bundle_sequence_id,
    batch_event_index,
    batch_page_id,
    batch_ordering_id,

    (
      SELECT ep.value.int_value
      FROM UNNEST(event_params) ep
      WHERE ep.key = 'ga_session_id'
    ) AS ga_session_id,

    (
      SELECT ep.value.string_value
      FROM UNNEST(event_params) ep
      WHERE ep.key = 'page_location'
    ) AS page_url,

    (
      SELECT ep.value.string_value
      FROM UNNEST(event_params) ep
      WHERE ep.key = 'page_title'
    ) AS page_title,

    (
      SELECT ep.value.string_value
      FROM UNNEST(event_params) ep
      WHERE ep.key = 'cta_name'
    ) AS cta_name,

    (
      SELECT ep.value.string_value
      FROM UNNEST(event_params) ep
      WHERE ep.key = 'cta_type'
    ) AS cta_type,

    (
      SELECT ep.value.string_value
      FROM UNNEST(event_params) ep
      WHERE ep.key = 'cta_location'
    ) AS cta_location,

    (
      SELECT ep.value.string_value
      FROM UNNEST(event_params) ep
      WHERE ep.key = 'destination_url'
    ) AS destination_url

  FROM `hotspawn-440312.analytics_457395054.events_*`

  WHERE event_name IN ('cta_impression', 'cta_click')

    AND _TABLE_SUFFIX BETWEEN
      FORMAT_DATE(
        '%Y%m%d',
        DATE_SUB(
          CURRENT_DATE('${dataform.projectConfig.vars.tz}'),
          INTERVAL ${dataform.projectConfig.vars.lookback_days}-1 DAY
        )
      )
      AND FORMAT_DATE(
        '%Y%m%d',
        CURRENT_DATE('${dataform.projectConfig.vars.tz}')
      )
),

filtered AS (
  SELECT *
  FROM base

  WHERE ga_session_id IS NOT NULL

    AND NOT EXISTS (
      SELECT 1
      FROM url_exclusions e
      WHERE LOWER(page_url) LIKE CONCAT('%', e.domain, '%')
    )
),

deduplicated AS (
  SELECT *
  FROM filtered

  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY
      event_timestamp,
      event_name,
      user_pseudo_id,
      ga_session_id,
      page_url,
      page_title,
      cta_name,
      cta_type,
      cta_location,
      destination_url,
      event_bundle_sequence_id,
      batch_page_id,
      batch_ordering_id
    ORDER BY
      batch_event_index
  ) = 1
)

SELECT
  event_ts,
  event_date,
  event_name,

  user_pseudo_id,
  ga_session_id,

  page_url,
  page_title,

  cta_name,
  cta_type,
  cta_location,
  destination_url,

  event_bundle_sequence_id,
  batch_event_index,
  batch_page_id,
  batch_ordering_id

FROM deduplicated